import React, { useState } from "react";
import {
  ArrowLeftIcon,
  CheckCircleIcon,
  ExclamationTriangleIcon,
  LinkIcon,
  CogIcon,
  CloudIcon,
  EnvelopeIcon,
  ChatBubbleLeftRightIcon,
  CreditCardIcon,
  PhoneIcon,
  DocumentTextIcon,
  ChartBarIcon,
  XMarkIcon,
} from "@heroicons/react/24/outline";
import { Button } from "./components/ui/button";

// Mock integration data
const integrations = [
  {
    id: "resend",
    name: "Resend",
    type: "Email Channel",
    description: "Modern email API for developers",
    logo: "https://resend.com/favicon.ico",
    status: "not_connected",
    category: "email",
    features: [
      "Transactional emails",
      "Email templates",
      "Analytics",
      "Webhooks",
    ],
    pricing: "Free tier available",
  },
  {
    id: "sendgrid",
    name: "SendGrid",
    type: "Email Channel",
    description: "Reliable email delivery platform",
    logo: "https://sendgrid.com/favicon.ico",
    status: "not_connected",
    category: "email",
    features: [
      "Bulk email",
      "Email validation",
      "Deliverability",
      "A/B testing",
    ],
    pricing: "Free tier available",
  },
  {
    id: "twilio",
    name: "Twilio",
    type: "SMS Channel",
    description: "Cloud communications platform",
    logo: "https://twilio.com/favicon.ico",
    status: "not_connected",
    category: "sms",
    features: ["SMS messaging", "Voice calls", "WhatsApp", "Phone numbers"],
    pricing: "Pay per use",
  },
  {
    id: "stripe",
    name: "Stripe",
    type: "Payment Partner",
    description: "Online payment processing",
    logo: "https://stripe.com/favicon.ico",
    status: "not_connected",
    category: "payment",
    features: [
      "Payment processing",
      "Subscriptions",
      "Invoicing",
      "Fraud protection",
    ],
    pricing: "2.9% + 30¢ per transaction",
  },
  {
    id: "intercom",
    name: "Intercom",
    type: "Chat Channel",
    description: "Customer messaging platform",
    logo: "https://intercom.com/favicon.ico",
    status: "not_connected",
    category: "chat",
    features: ["Live chat", "Help desk", "Bots", "Customer data"],
    pricing: "Free tier available",
  },
  {
    id: "hubspot",
    name: "HubSpot",
    type: "CRM Integration",
    description: "All-in-one CRM platform",
    logo: "https://hubspot.com/favicon.ico",
    status: "not_connected",
    category: "crm",
    features: [
      "Contact management",
      "Marketing automation",
      "Sales pipeline",
      "Analytics",
    ],
    pricing: "Free tier available",
  },
];

const categories = [
  { id: "all", name: "All", icon: CloudIcon },
  { id: "email", name: "Email", icon: EnvelopeIcon },
  { id: "sms", name: "SMS", icon: PhoneIcon },
  { id: "chat", name: "Chat", icon: ChatBubbleLeftRightIcon },
  { id: "payment", name: "Payment", icon: CreditCardIcon },
  { id: "crm", name: "CRM", icon: ChartBarIcon },
  { id: "custom", name: "Custom", icon: CogIcon },
];

export default function Integration() {
  const [activeTab, setActiveTab] = useState("marketplace");
  const [selectedCategory, setSelectedCategory] = useState("all");
  const [connectingIntegration, setConnectingIntegration] = useState(null);
  const [connectionStep, setConnectionStep] = useState(1);
  const [apiKey, setApiKey] = useState("");
  const [domains, setDomains] = useState([]);
  const [newDomain, setNewDomain] = useState("");
  const [selectedDomain, setSelectedDomain] = useState(null);
  const [virtualId, setVirtualId] = useState("");
  const [showVirtualIdForm, setShowVirtualIdForm] = useState(false);
  const [showSidePanel, setShowSidePanel] = useState(false);

  // DNS Records for Resend
  const dnsRecords = {
    mx: {
      type: "MX",
      purpose: "Mail Exchange",
      host: "send",
      value: "feedback-smtp.us-east-1.amazonses.com",
      priority: 10,
    },
    spf: {
      type: "TXT",
      purpose: "Sender Policy Framework",
      host: "send",
      value: '"v=spf1 include:amazonses.com ~all"',
    },
    dkim: {
      type: "TXT",
      purpose: "DomainKeys Identified Mail",
      host: "resend._domainkey",
      value: "Generated by Resend",
    },
  };

  // Filter integrations by category
  const filteredIntegrations =
    selectedCategory === "all"
      ? integrations
      : integrations.filter(
          (integration) => integration.category === selectedCategory
        );

  const handleConnect = (integration) => {
    setConnectingIntegration(integration);
    setConnectionStep(1);
    setApiKey("");
    setDomains([]);
    setNewDomain("");
    setSelectedDomain(null);
    setVirtualId("");
    setShowVirtualIdForm(false);
    setShowSidePanel(true);
  };

  const handleApiKeySubmit = () => {
    if (apiKey.trim()) {
      setConnectionStep(2); // Move to domain setup
    }
  };

  const handleDomainSubmit = () => {
    console.log("handleDomainSubmit called with newDomain:", newDomain);
    if (newDomain.trim()) {
      const domain = {
        id: Date.now(),
        name: newDomain,
        verified: false,
        dnsRecords: dnsRecords,
        virtualIds: [],
      };
      console.log("Adding domain:", domain);
      setDomains([...domains, domain]);
      setNewDomain("");
      setConnectionStep(4); // Move to DNS verification
      console.log("Moving to step 4");
    } else {
      console.log("Domain name is empty");
    }
  };

  const handleVerifyDomain = (domainId) => {
    setDomains(
      domains.map((domain) =>
        domain.id === domainId ? { ...domain, verified: true } : domain
      )
    );
    setConnectionStep(5); // Move to domain management
  };

  const handleCreateVirtualId = (domainId) => {
    setSelectedDomain(domains.find((d) => d.id === domainId));
    setShowVirtualIdForm(true);
  };

  const handleVirtualIdSubmit = () => {
    if (virtualId.trim() && selectedDomain) {
      const newVirtualId = {
        id: Date.now(),
        name: virtualId,
        email: `${virtualId}@send.${selectedDomain.name}`,
        domain: selectedDomain.name,
      };

      setDomains(
        domains.map((domain) =>
          domain.id === selectedDomain.id
            ? { ...domain, virtualIds: [...domain.virtualIds, newVirtualId] }
            : domain
        )
      );

      setVirtualId("");
      setShowVirtualIdForm(false);
      setSelectedDomain(null);
    }
  };

  const handleConnectionComplete = () => {
    setConnectingIntegration(null);
    setConnectionStep(1);
    setApiKey("");
    setDomains([]);
    setNewDomain("");
    setSelectedDomain(null);
    setVirtualId("");
    setShowVirtualIdForm(false);
    setShowSidePanel(false);
  };

  const getStatusColor = (status) => {
    switch (status) {
      case "connected":
        return "bg-green-100 text-green-800 border-green-200";
      case "connecting":
        return "bg-yellow-100 text-yellow-800 border-yellow-200";
      case "error":
        return "bg-red-100 text-red-800 border-red-200";
      default:
        return "bg-gray-100 text-gray-800 border-gray-200";
    }
  };

  const getStatusIcon = (status) => {
    switch (status) {
      case "connected":
        return <CheckCircleIcon className="w-4 h-4" />;
      case "error":
        return <ExclamationTriangleIcon className="w-4 h-4" />;
      default:
        return <LinkIcon className="w-4 h-4" />;
    }
  };

  const renderMarketplace = () => (
    <div className="space-y-6">
      {/* Category Filter */}
      <div className="flex flex-wrap gap-2">
        {categories.map((category) => {
          const Icon = category.icon;
          return (
            <button
              key={category.id}
              onClick={() => setSelectedCategory(category.id)}
              className={`px-4 py-2 rounded-lg text-sm font-medium flex items-center space-x-2 transition-colors ${
                selectedCategory === category.id
                  ? "bg-gray-900 text-white"
                  : "bg-gray-100 text-gray-700 hover:bg-gray-200"
              }`}
            >
              <Icon className="w-4 h-4" />
              <span>{category.name}</span>
            </button>
          );
        })}
      </div>

      {/* Integration Cards */}
      <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
        {filteredIntegrations.map((integration) => (
          <div
            key={integration.id}
            className="bg-white border border-gray-200 rounded-lg p-6 hover:shadow-md transition-shadow"
          >
            <div className="flex items-start justify-between mb-4">
              <div className="flex items-center space-x-3">
                <div className="w-10 h-10 bg-gray-100 rounded-lg flex items-center justify-center">
                  <img
                    src={integration.logo}
                    alt={`${integration.name} logo`}
                    className="w-6 h-6"
                    onError={(e) => {
                      e.target.style.display = "none";
                    }}
                  />
                </div>
                <div>
                  <h3 className="font-semibold text-gray-900">
                    {integration.name}
                  </h3>
                  <p className="text-sm text-gray-500">{integration.type}</p>
                </div>
              </div>
              <span
                className={`inline-flex items-center px-2 py-1 rounded-full text-xs font-medium border ${getStatusColor(
                  integration.status
                )}`}
              >
                {getStatusIcon(integration.status)}
                <span className="ml-1">
                  {integration.status === "connected"
                    ? "Connected"
                    : "Not Connected"}
                </span>
              </span>
            </div>

            <p className="text-sm text-gray-600 mb-4">
              {integration.description}
            </p>

            <div className="space-y-3 mb-4">
              <div className="text-xs text-gray-500">Key Features:</div>
              <div className="flex flex-wrap gap-1">
                {integration.features.slice(0, 3).map((feature, index) => (
                  <span
                    key={index}
                    className="px-2 py-1 bg-gray-100 text-gray-700 text-xs rounded"
                  >
                    {feature}
                  </span>
                ))}
                {integration.features.length > 3 && (
                  <span className="px-2 py-1 bg-gray-100 text-gray-700 text-xs rounded">
                    +{integration.features.length - 3} more
                  </span>
                )}
              </div>
            </div>

            <div className="flex items-center justify-between">
              <span className="text-xs text-gray-500">
                {integration.pricing}
              </span>
              <Button
                onClick={() => handleConnect(integration)}
                size="sm"
                className={`${
                  integration.status === "connected"
                    ? "bg-green-600 hover:bg-green-700 text-white"
                    : "bg-gray-900 hover:bg-gray-800 text-white"
                }`}
              >
                {integration.status === "connected" ? "Manage" : "Connect"}
              </Button>
            </div>
          </div>
        ))}
      </div>
    </div>
  );

  const renderCustomIntegration = () => (
    <div className="space-y-6">
      <div className="bg-white border border-gray-200 rounded-lg p-8">
        <div className="text-center">
          <CogIcon className="w-12 h-12 text-gray-400 mx-auto mb-4" />
          <h3 className="text-lg font-semibold text-gray-900 mb-2">
            Custom Integration
          </h3>
          <p className="text-gray-600 mb-6">
            Build custom integrations with our API or webhook system
          </p>
          <div className="space-y-4">
            <Button className="bg-gray-900 hover:bg-gray-800 text-white">
              View API Documentation
            </Button>
            <Button variant="outline" className="ml-4">
              Setup Webhooks
            </Button>
          </div>
        </div>
      </div>

      <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
        <div className="bg-white border border-gray-200 rounded-lg p-6">
          <h4 className="font-semibold text-gray-900 mb-3">API Integration</h4>
          <p className="text-sm text-gray-600 mb-4">
            Use our REST API to integrate with your existing systems
          </p>
          <ul className="text-sm text-gray-600 space-y-2">
            <li>• RESTful API endpoints</li>
            <li>• Authentication with API keys</li>
            <li>• Rate limiting and quotas</li>
            <li>• Comprehensive documentation</li>
          </ul>
        </div>

        <div className="bg-white border border-gray-200 rounded-lg p-6">
          <h4 className="font-semibold text-gray-900 mb-3">
            Webhook Integration
          </h4>
          <p className="text-sm text-gray-600 mb-4">
            Receive real-time notifications about events in your system
          </p>
          <ul className="text-sm text-gray-600 space-y-2">
            <li>• Real-time event notifications</li>
            <li>• Secure webhook signatures</li>
            <li>• Retry mechanisms</li>
            <li>• Event filtering</li>
          </ul>
        </div>
      </div>
    </div>
  );

  const renderSidePanel = () => {
    if (!showSidePanel || !connectingIntegration) return null;

    return (
      <div className="fixed inset-0 bg-black bg-opacity-50 z-50">
        <div className="absolute right-0 top-0 h-full w-full max-w-2xl bg-white shadow-xl overflow-y-auto">
          <div className="p-6">
            <div className="flex items-center justify-between mb-6">
              <h3 className="text-lg font-semibold text-gray-900">
                Connect {connectingIntegration.name}
              </h3>
              <button
                onClick={() => setShowSidePanel(false)}
                className="text-gray-400 hover:text-gray-600"
              >
                <XMarkIcon className="w-6 h-6" />
              </button>
            </div>

            {/* Step 1: API Key */}
            {connectionStep === 1 && (
              <div className="space-y-4">
                <div className="flex items-center space-x-3 p-4 bg-gray-50 rounded-lg">
                  <img
                    src={connectingIntegration.logo}
                    alt={`${connectingIntegration.name} logo`}
                    className="w-8 h-8"
                  />
                  <div>
                    <h4 className="font-medium text-gray-900">
                      {connectingIntegration.name}
                    </h4>
                    <p className="text-sm text-gray-500">
                      {connectingIntegration.type}
                    </p>
                  </div>
                </div>

                <div className="space-y-3">
                  <div>
                    <label className="block text-sm font-medium text-gray-700 mb-1">
                      API Key
                    </label>
                    <input
                      type="password"
                      value={apiKey}
                      onChange={(e) => setApiKey(e.target.value)}
                      className="w-full px-3 py-2 border border-gray-300 rounded-md focus:outline-none focus:ring-2 focus:ring-gray-500 focus:border-transparent"
                      placeholder="Enter your Resend API key"
                    />
                  </div>
                </div>

                <div className="flex justify-end space-x-3">
                  <Button
                    variant="outline"
                    onClick={() => setConnectingIntegration(null)}
                  >
                    Cancel
                  </Button>
                  <Button
                    onClick={handleApiKeySubmit}
                    disabled={!apiKey.trim()}
                    className="bg-gray-900 hover:bg-gray-800 text-white"
                  >
                    Next
                  </Button>
                </div>
              </div>
            )}

            {/* Step 2: Empty State or Domain Setup */}
            {connectionStep === 2 && (
              <div className="space-y-6">
                <div className="text-center">
                  <div className="w-16 h-16 bg-green-100 rounded-full flex items-center justify-center mx-auto mb-4">
                    <CheckCircleIcon className="w-8 h-8 text-green-600" />
                  </div>
                  <h4 className="text-lg font-semibold text-gray-900 mb-2">
                    API Key Verified!
                  </h4>
                  <p className="text-gray-600 mb-6">
                    Now let's set up your domain for email sending.
                  </p>
                </div>

                {domains.length === 0 ? (
                  <div className="text-center py-12">
                    <CloudIcon className="w-16 h-16 text-gray-300 mx-auto mb-4" />
                    <h5 className="text-lg font-medium text-gray-900 mb-2">
                      No Domains Added
                    </h5>
                    <p className="text-gray-500 mb-6">
                      Add your first domain to start sending emails
                    </p>
                    <Button
                      onClick={() => setConnectionStep(3)}
                      className="bg-gray-900 hover:bg-gray-800 text-white"
                    >
                      Generate DNS Records
                    </Button>
                  </div>
                ) : (
                  <div className="space-y-4">
                    <div className="flex items-center justify-between">
                      <h5 className="font-medium text-gray-900">
                        Your Domains
                      </h5>
                      <Button
                        onClick={() => setConnectionStep(3)}
                        size="sm"
                        className="bg-gray-900 hover:bg-gray-800 text-white"
                      >
                        Generate DNS Records
                      </Button>
                    </div>

                    {domains.map((domain) => (
                      <div key={domain.id} className="border rounded-lg p-4">
                        <div className="flex items-center justify-between">
                          <div>
                            <h6 className="font-medium text-gray-900">
                              {domain.name}
                            </h6>
                            <p className="text-sm text-gray-500">
                              send.{domain.name}
                            </p>
                          </div>
                          <span
                            className={`px-2 py-1 rounded-full text-xs font-medium ${
                              domain.verified
                                ? "bg-green-100 text-green-800"
                                : "bg-yellow-100 text-yellow-800"
                            }`}
                          >
                            {domain.verified ? "Verified" : "Pending"}
                          </span>
                        </div>
                      </div>
                    ))}
                  </div>
                )}

                <div className="flex justify-end space-x-3">
                  <Button
                    variant="outline"
                    onClick={() => setConnectionStep(1)}
                  >
                    Back
                  </Button>
                  {domains.length > 0 && (
                    <Button
                      onClick={handleConnectionComplete}
                      className="bg-gray-900 hover:bg-gray-800 text-white"
                    >
                      Complete Setup
                    </Button>
                  )}
                </div>
              </div>
            )}

            {/* Step 3: Domain Setup Form */}
            {connectionStep === 3 && (
              <div className="space-y-6">
                <div className="text-center">
                  <h4 className="text-lg font-semibold text-gray-900 mb-2">
                    Generate DNS Records
                  </h4>
                  <p className="text-gray-600 mb-6">
                    Enter your domain name to generate the required DNS records.
                  </p>
                </div>

                <div className="space-y-3">
                  <div>
                    <label className="block text-sm font-medium text-gray-700 mb-1">
                      Domain Name
                    </label>
                    <input
                      type="text"
                      value={newDomain}
                      onChange={(e) => setNewDomain(e.target.value)}
                      className="w-full px-3 py-2 border border-gray-300 rounded-md focus:outline-none focus:ring-2 focus:ring-gray-500 focus:border-transparent"
                      placeholder="Enter your domain (e.g., abc.com)"
                    />
                    <p className="text-xs text-gray-500 mt-1">
                      This will create send.abc.com for sending emails
                    </p>
                  </div>
                </div>

                {newDomain.trim() && (
                  <div className="space-y-4">
                    <div className="bg-gray-50 rounded-lg p-4">
                      <h5 className="font-semibold text-gray-900 mb-3">
                        Required DNS Records for {newDomain}
                      </h5>
                      <div className="space-y-3">
                        {Object.entries(dnsRecords).map(([key, record]) => (
                          <div
                            key={key}
                            className="bg-white rounded-lg p-3 border"
                          >
                            <div className="flex items-center justify-between mb-2">
                              <span className="font-medium text-sm text-gray-900">
                                {record.type} Record
                              </span>
                              <span className="text-xs text-gray-500">
                                {record.purpose}
                              </span>
                            </div>
                            <div className="space-y-1 text-sm">
                              <div>
                                <span className="text-gray-600">
                                  Host/Name:
                                </span>
                                <span className="ml-2 font-mono bg-gray-100 px-2 py-1 rounded">
                                  {record.host}
                                </span>
                              </div>
                              <div>
                                <span className="text-gray-600">Value:</span>
                                <span className="ml-2 font-mono bg-gray-100 px-2 py-1 rounded text-xs">
                                  {record.value}
                                </span>
                              </div>
                              {record.priority && (
                                <div>
                                  <span className="text-gray-600">
                                    Priority:
                                  </span>
                                  <span className="ml-2 font-mono bg-gray-100 px-2 py-1 rounded">
                                    {record.priority}
                                  </span>
                                </div>
                              )}
                            </div>
                          </div>
                        ))}
                      </div>
                    </div>
                  </div>
                )}

                <div className="flex justify-end space-x-3">
                  <Button
                    variant="outline"
                    onClick={() => setConnectionStep(2)}
                  >
                    Back
                  </Button>
                  <Button
                    onClick={handleDomainSubmit}
                    disabled={!newDomain.trim()}
                    className="bg-gray-900 hover:bg-gray-800 text-white"
                  >
                    Verify Domain
                  </Button>
                </div>
              </div>
            )}

            {/* Step 4: DNS Verification */}
            {connectionStep === 4 && (
              <div className="space-y-4">
                <div className="text-center">
                  <h4 className="text-lg font-semibold text-gray-900 mb-2">
                    Configure DNS Records
                  </h4>
                  <p className="text-gray-600 mb-6">
                    Add these DNS records to verify domain ownership and ensure
                    deliverability.
                  </p>
                </div>

                <div className="bg-gray-50 rounded-lg p-4">
                  <h5 className="font-semibold text-gray-900 mb-3">
                    Required DNS Records
                  </h5>
                  <div className="space-y-3">
                    {Object.entries(dnsRecords).map(([key, record]) => (
                      <div key={key} className="bg-white rounded-lg p-3 border">
                        <div className="flex items-center justify-between mb-2">
                          <span className="font-medium text-sm text-gray-900">
                            {record.type} Record
                          </span>
                          <span className="text-xs text-gray-500">
                            {record.purpose}
                          </span>
                        </div>
                        <div className="space-y-1 text-sm">
                          <div>
                            <span className="text-gray-600">Host/Name:</span>
                            <span className="ml-2 font-mono bg-gray-100 px-2 py-1 rounded">
                              {record.host}
                            </span>
                          </div>
                          <div>
                            <span className="text-gray-600">Value:</span>
                            <span className="ml-2 font-mono bg-gray-100 px-2 py-1 rounded text-xs">
                              {record.value}
                            </span>
                          </div>
                          {record.priority && (
                            <div>
                              <span className="text-gray-600">Priority:</span>
                              <span className="ml-2 font-mono bg-gray-100 px-2 py-1 rounded">
                                {record.priority}
                              </span>
                            </div>
                          )}
                        </div>
                      </div>
                    ))}
                  </div>
                </div>

                <div className="flex justify-end space-x-3">
                  <Button
                    variant="outline"
                    onClick={() => setConnectionStep(3)}
                  >
                    Back
                  </Button>
                  <Button
                    onClick={() =>
                      handleVerifyDomain(domains[domains.length - 1]?.id)
                    }
                    className="bg-gray-900 hover:bg-gray-800 text-white"
                  >
                    Verify Domain
                  </Button>
                </div>
              </div>
            )}

            {/* Step 5: Domain Management */}
            {connectionStep === 5 && (
              <div className="space-y-4">
                <div className="text-center">
                  <h4 className="text-lg font-semibold text-gray-900 mb-2">
                    Domain Management
                  </h4>
                  <p className="text-gray-600 mb-6">
                    Manage your domains and create virtual email addresses.
                  </p>
                </div>

                <div className="space-y-4">
                  {domains.map((domain) => (
                    <div key={domain.id} className="border rounded-lg p-4">
                      <div className="flex items-center justify-between mb-3">
                        <div>
                          <h5 className="font-medium text-gray-900">
                            {domain.name}
                          </h5>
                          <p className="text-sm text-gray-500">
                            send.{domain.name}
                          </p>
                        </div>
                        <span
                          className={`px-2 py-1 rounded-full text-xs font-medium ${
                            domain.verified
                              ? "bg-green-100 text-green-800"
                              : "bg-yellow-100 text-yellow-800"
                          }`}
                        >
                          {domain.verified ? "Verified" : "Pending"}
                        </span>
                      </div>

                      {domain.verified && (
                        <div className="space-y-3">
                          <div>
                            <h6 className="text-sm font-medium text-gray-700 mb-2">
                              Virtual Email Addresses
                            </h6>
                            {domain.virtualIds.length > 0 ? (
                              <div className="space-y-2">
                                {domain.virtualIds.map((vid) => (
                                  <div
                                    key={vid.id}
                                    className="flex items-center justify-between bg-gray-50 rounded p-2"
                                  >
                                    <span className="text-sm font-mono">
                                      {vid.email}
                                    </span>
                                    <span className="text-xs text-gray-500">
                                      Active
                                    </span>
                                  </div>
                                ))}
                              </div>
                            ) : (
                              <p className="text-sm text-gray-500">
                                No virtual addresses created yet
                              </p>
                            )}
                          </div>
                          <Button
                            onClick={() => handleCreateVirtualId(domain.id)}
                            size="sm"
                            className="bg-gray-900 hover:bg-gray-800 text-white"
                          >
                            Create Virtual ID
                          </Button>
                        </div>
                      )}
                    </div>
                  ))}
                </div>

                <div className="flex justify-end space-x-3">
                  <Button
                    variant="outline"
                    onClick={() => setConnectionStep(2)}
                  >
                    Add Another Domain
                  </Button>
                  <Button
                    onClick={handleConnectionComplete}
                    className="bg-gray-900 hover:bg-gray-800 text-white"
                  >
                    Complete Setup
                  </Button>
                </div>
              </div>
            )}
          </div>
        </div>
      </div>
    );
  };

  return (
    <div className="min-h-screen bg-gray-50">
      {/* Header */}
      <div className="bg-white border-b border-gray-200">
        <div className="px-6 py-4">
          <div className="flex items-center justify-between">
            <div className="flex items-center space-x-4">
              <Button
                variant="outline"
                onClick={() => window.history.back()}
                className="flex items-center space-x-2"
              >
                <ArrowLeftIcon className="w-4 h-4" />
                <span>Back</span>
              </Button>
              <div>
                <h1 className="text-xl font-semibold text-gray-900">
                  Integrations
                </h1>
                <p className="text-sm text-gray-600">
                  Connect with third-party services
                </p>
              </div>
            </div>
          </div>
        </div>
      </div>

      {/* Tabs */}
      <div className="bg-white border-b border-gray-200">
        <div className="px-6">
          <div className="flex space-x-8">
            <button
              onClick={() => setActiveTab("marketplace")}
              className={`py-4 px-1 border-b-2 font-medium text-sm ${
                activeTab === "marketplace"
                  ? "border-gray-900 text-gray-900"
                  : "border-transparent text-gray-500 hover:text-gray-700 hover:border-gray-300"
              }`}
            >
              Marketplace
            </button>
            <button
              onClick={() => setActiveTab("custom")}
              className={`py-4 px-1 border-b-2 font-medium text-sm ${
                activeTab === "custom"
                  ? "border-gray-900 text-gray-900"
                  : "border-transparent text-gray-500 hover:text-gray-700 hover:border-gray-300"
              }`}
            >
              Custom Integration
            </button>
          </div>
        </div>
      </div>

      {/* Content */}
      <div className="p-6">
        {activeTab === "marketplace"
          ? renderMarketplace()
          : renderCustomIntegration()}
      </div>

      {/* Connection Side Panel */}
      {renderSidePanel()}

      {/* Virtual ID Creation Modal */}
      {showVirtualIdForm && selectedDomain && (
        <div className="fixed inset-0 bg-black bg-opacity-50 flex items-center justify-center z-50">
          <div className="bg-white rounded-lg p-6 w-full max-w-md mx-4">
            <div className="flex items-center justify-between mb-4">
              <h3 className="text-lg font-semibold text-gray-900">
                Create Virtual Email Address
              </h3>
              <button
                onClick={() => {
                  setShowVirtualIdForm(false);
                  setSelectedDomain(null);
                  setVirtualId("");
                }}
                className="text-gray-400 hover:text-gray-600"
              >
                ×
              </button>
            </div>

            <div className="space-y-4">
              <div className="p-4 bg-gray-50 rounded-lg">
                <h4 className="font-medium text-gray-900 mb-1">
                  Domain: {selectedDomain.name}
                </h4>
                <p className="text-sm text-gray-500">
                  Emails will be sent from: send.{selectedDomain.name}
                </p>
              </div>

              <div>
                <label className="block text-sm font-medium text-gray-700 mb-1">
                  Virtual ID
                </label>
                <div className="flex items-center space-x-2">
                  <input
                    type="text"
                    value={virtualId}
                    onChange={(e) => setVirtualId(e.target.value)}
                    className="flex-1 px-3 py-2 border border-gray-300 rounded-md focus:outline-none focus:ring-2 focus:ring-gray-500 focus:border-transparent"
                    placeholder="Enter ID (e.g., support)"
                  />
                  <span className="text-sm text-gray-500">
                    @send.{selectedDomain.name}
                  </span>
                </div>
                <p className="text-xs text-gray-500 mt-1">
                  This will create: {virtualId || "support"}@send.
                  {selectedDomain.name}
                </p>
              </div>

              <div className="flex justify-end space-x-3">
                <Button
                  variant="outline"
                  onClick={() => {
                    setShowVirtualIdForm(false);
                    setSelectedDomain(null);
                    setVirtualId("");
                  }}
                >
                  Cancel
                </Button>
                <Button
                  onClick={handleVirtualIdSubmit}
                  disabled={!virtualId.trim()}
                  className="bg-gray-900 hover:bg-gray-800 text-white"
                >
                  Create Virtual ID
                </Button>
              </div>
            </div>
          </div>
        </div>
      )}
    </div>
  );
}
